### ISSUE TITLE
Pr's wont be automatically merged

### ISSUE THREAD

**Issue by notMEEPoffaith** [sample-text-here/community-mod#133]
You can attach screenshots if needed.

**Game version and other mods installed:**
not in game

**Describe the issue:**
a PR wont be automerged, like when i tried to add in a new unit.

**Steps to reproduce the bug:**
step 1: make thing
step 2: pr

**Device and OS version:**
not needed, it's a problem with the bot

**Comment by amg2048** [comment]
wontfix label
![image](https://user-images.githubusercontent.com/82839009/125081498-12cae300-e094-11eb-8250-bfff3d2e4eb8.png)

**Comment by sample-text-here** [comment]
it was merged anyway
