### ISSUE TITLE
egg

### ISSUE THREAD

**Issue by Erisfiregamer1** [sample-text-here/community-mod#135]
ě̴̛̛̠̮̙͓͇̱̩̤̘͎̪̹̾̆̈̈͛́͊̏̑̀̔̌͂͑̇̒͒̄̉̄͊͌̇̌̓͗̽͂̎͘͘͘͜͝͝͠͠͝ģ̸̡̡̡̛̙̫̘̻̥͚̞͔̥̩̲̜̲̗̝̼̣̝͖̩̰̗̙̤̼̗̮̱͖̺̗̦̬̝̤̳̉͛̐̀̈́͊͋́̇͌̂̆͛̈͂̕͘͘͜͜g̷̡̧̧̗͇̦̳̣̥̮̩̱̩̬̦͉̳͔̦̼̔̈̔̍͒ͅ

**Comment by Erisfiregamer1** [comment]
**_ě̴̛̛̠̮̙͓͇̱̩̤̘͎̪̹̾̆̈̈͛́͊̏̑̀̔̌͂͑̇̒͒̄̉̄͊͌̇̌̓͗̽͂̎͘͘͘͜͝͝͠͠͝ģ̸̡̡̡̛̙̫̘̻̥͚̞͔̥̩̲̜̲̗̝̼̣̝͖̩̰̗̙̤̼̗̮̱͖̺̗̦̬̝̤̳̉͛̐̀̈́͊͋́̇͌̂̆͛̈͂̕͘͘͜͜g̷̡̧̧̗͇̦̳̣̥̮̩̱̩̬̦͉̳͔̦̼̔̈̔̍͒ͅ_**

**Comment by ifritdiezel** [comment]
https://github.com/sample-text-here/community-mod/issues/15
