### ISSUE TITLE
so what is content this mod will have???????

### ISSUE THREAD

**Issue by lokyinng** [sample-text-here/community-mod#137]
oh so your are one of the modder of community mod name all content of the community mod and all block, unit, liquid, item, weather of mindustry

**Comment by USMP-lancer** [comment]
it will have, alot

**Comment by USMP-lancer** [comment]
its very cursed

**Comment by ifritdiezel** [comment]
yes this mod will have content

**Comment by USMP-lancer** [comment]
it should be renaming you to pepsi
